version: '3.9'
services:
  authGo:
    image: navachar/kotlang-auth:3041e22e96bc97c213330b658c6b5857f6851766
    env_file:
      - .env
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
  socialGo:
    image: navachar/kotlang-social:b4ad8cfb12f8c5e269290a3ea4a8a8fd31b5c8db
    env_file:
      - .env
    environment:
      - AUTH_TARGET=authGo:50051
      - NOTIFICATION_TARGET=notificationGo:50051
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}

  notificationGo:
    image: navachar/kotlang-notification:ea6e8ed11a9089a4d55b3409bc6bbf96aa5bdd90
    env_file:
      - .env
    environment:
      - SOCIAL_TARGET=socialGo:50051
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}

  localizationGo:
    image: navachar/kotlang-localizer:70e78066380ad0e0100b7c5d2babc0d9309d3740
    env_file:
      - .env
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
  navacharApp:
    image: navachar/kotlang-navacharapp:73c257bae9fff1eb421b6fbe13cf17897c46cdd0
    environment:
      - SOCIAL_TARGET=socialGo:50051
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
  navacharAdminPanel:
    image: navachar/kotlang-navachar-admin-panel:29c8734d54f4deeb36563c5292a5a4b8a7d44bce
  navacharWebsite:
    image: navachar/kotlang-navachar-website:8065708b568f254f6df29a0b5d7575165ad98ea0
  nginx:
    image: nginx:1.19.6
    ports:
      - "50051:50051"
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - authGo
      - socialGo
      - localizationGo
      - navacharApp
      - navacharWebsite
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
